projects:
  genes-cicciac:
    schemaPath: Users/vchap/Desktop/Guessepe/istopWebsite/src/graphql/schema.json
    includes:
      - src/graphql/**/*.ts
    excludes:
      - ./amplify/**
      - src/API.ts
    extensions:
      amplify:
        codeGenTarget: typescript
        generatedFileName: src/API.ts
        docsFilePath: src/graphql
        region: us-east-1
        apiId: fcjyse2b3fgljlfbpa5tsoe3gq
extensions:
  amplify:
    version: 3
